// flow-typed signature: 62ee31b907716c28bfd7b5c3572c23a3
// flow-typed version: <<STUB>>/gql2flow_v^0.4.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gql2flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gql2flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gql2flow/util/fetcher' {
  declare module.exports: any;
}

declare module 'gql2flow/util/fileIO' {
  declare module.exports: any;
}

declare module 'gql2flow/util/interface' {
  declare module.exports: any;
}

declare module 'gql2flow/util/module' {
  declare module.exports: any;
}

declare module 'gql2flow/util/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gql2flow/index' {
  declare module.exports: $Exports<'gql2flow'>;
}
declare module 'gql2flow/index.js' {
  declare module.exports: $Exports<'gql2flow'>;
}
declare module 'gql2flow/util/fetcher.js' {
  declare module.exports: $Exports<'gql2flow/util/fetcher'>;
}
declare module 'gql2flow/util/fileIO.js' {
  declare module.exports: $Exports<'gql2flow/util/fileIO'>;
}
declare module 'gql2flow/util/interface.js' {
  declare module.exports: $Exports<'gql2flow/util/interface'>;
}
declare module 'gql2flow/util/module.js' {
  declare module.exports: $Exports<'gql2flow/util/module'>;
}
declare module 'gql2flow/util/polyfill.js' {
  declare module.exports: $Exports<'gql2flow/util/polyfill'>;
}
